---
global:
  evaluation_interval: 5s
  scrape_interval: 5s
scrape_configs:
  -
    job_name: kafka
    static_configs:
      -
        targets:
          - "kafka:7071"
  -
    job_name: prometheus
    static_configs:
      -
        targets:
          - "prometheus:9090"
  -
    job_name: node
    static_configs:
      -
        targets:
          - "kafka:9100"
