version: '2'

services:

  alertmanager:
    image: prom/alertmanager
    hostname: alertmanager
    container_name: alertmanager
    restart: always
    volumes:
      - ./alertmanager/data:/alertmanager
      - ./alertmanager/conf/config.yml:/etc/alertmanager/config.yml

  prometheus:
    image: prom/prometheus:v2.1.0
    hostname: prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/conf:/etc/prometheus
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:4.6.3
    hostname: grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana

  snmpd:
    image: polinux/snmpd:alpine
    hostname: snmpd
    container_name: snmpd
    cap_add:
      - NET_ADMIN
    ports:
      - 161:161/udp
    volumes:
      - ./snmpd/conf/snmpd.conf:/etc/snmp/snmpd.conf

  snmp-exporter:
    image: prom/snmp-exporter
    hostname: snmp-exporter
    container_name: snmp-exporter
    volumes:
      - ./snmp-exporter/conf/snmp.yml:/etc/snmp_exporter/snmp.yml

  node1:
    image: prom/node-exporter
    hostname: node1
    container_name: node1

  node2:
    image: prom/node-exporter
    hostname: node2
    container_name: node2

  kafka:
    image: jazzwang/kafka:latest
    hostname: kafka
    container_name: kafka
    restart: always
    ports:
      - 2181:2181
      - 9092:9092
    volumes:
      - ./kafka-broker:/etc/kafka
    environment:
      - KAFKA_OPTS=-javaagent:/etc/kafka/jmx_prometheus_javaagent.jar=7071:/etc/kafka/kafka-jmx.yml
      - JMX_PORT=9999

  kafka-manager:
    image: sheepkiller/kafka-manager
    hostname: kafka-manager
    container_name: kafka-manager
    restart: always
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=kafka:2181
      - JAVA_OPTS=-Xmx512m
      - APPLICATION_SECRET=letmein

###################################################################
## NOTE: this kafka-exporter is for Kafka version less than 0.10 ##
###################################################################
#  kafka-exporter:
#    build: ./kafka-exporter
#    image: jazzwang/kafka-exporter:0.1.0
#    hostname: kafka-exporter
#    container_name: kafka-exporter
#    restart: always
#    depends_on:
#      - kafka
#    command: /usr/bin/kafka_exporter -zookeeper-connect kafka:2181 -listen-address ':9101'

  kafka-exporter:
    image: danielqsj/kafka-exporter
    hostname: kafka-exporter
    container_name: kafka-exporter
    restart: always
    depends_on:
      - kafka
    command: --kafka.server=kafka:9092

  cassandra:
    image: cassandra
    hostname: cassandra
    container_name: cassandra
    restart: always
    volumes:
      - ./cassandra:/data/cassandra
    environment:
      - JVM_OPTS=-javaagent:/data/cassandra/jmx_prometheus_javaagent.jar=7070:/data/cassandra/cdra-jmx.yml

  fluentd:
    build: ./fluentd
    image: jazzwang/fluentd:v1.0
    hostname: fluentd
    container_name: fluentd
    restart: always
    depends_on:
      - kafka
    volumes:
      - ./fluentd/etc:/fluentd/etc
      - ./fluentd/data:/tmp

  fluentd-exporter:
    build: ./fluentd-exporter
    image: jazzwang/fluentd-exporter:0.1.0
    hostname: fluentd-exporter
    container_name: fluentd-exporter
    restart: always
    depends_on:
      - fluentd
    command: fluentd_exporter -scrape_uri http://fluentd:24220/api/plugins.json

  client:
    build: ./client
    image: jazzwang/client
    hostname: client
    container_name: client
    restart: always
    stdin_open: true
    tty: true
    command: /bin/sh
