---
alerting:
  alertmanagers:
    -
      static_configs:
        -
          targets:
            - "alertmanager:9093"
global:
  evaluation_interval: 5s
  scrape_interval: 5s
scrape_configs:
  -
    job_name: cassandra
    static_configs:
      -
        targets:
          - "cassandra:7070"
  -
    job_name: kafka
    static_configs:
      -
        targets:
          - "kafka:7071"
  -
    job_name: kafka-exporter
    static_configs:
      -
        targets:
          - "kafka-exporter:9308"
  -
    job_name: fluentd
    static_configs:
      -
        targets:
          - "fluentd-exporter:9309"
  -
    job_name: grafana
    static_configs:
      -
        targets:
          - "grafana:3000"
  -
    job_name: prometheus
    static_configs:
      -
        targets:
          - "prometheus:9090"
  -
    job_name: snmp
    metrics_path: /snmp
    params:
      module:
        - if_mib
    relabel_configs:
      -
        source_labels:
          - __address__
        target_label: __param_target
      -
        source_labels:
          - __param_target
        target_label: instance
      -
        replacement: "snmp-exporter:9116"
        target_label: __address__
    static_configs:
      -
        targets:
          - "snmpd"
